apiVersion: v1
kind: ConfigMap
metadata:
  name: trieve-server-config
data:
  ADMIN_API_KEY: {{ .Values.config.trieve.adminApiKey }}
  BASE_SERVER_URL: {{ .Values.config.trieve.baseServerUrl }}
  DATABASE_URL: {{ include "trieve.databaseUrl" . | indent 2 }}
  REDIS_URL: {{ include "trieve.redisUrl" . | indent 2 }}
  QDRANT_URL: {{ .Values.config.qdrant.qdrantUrl }}
  QDRANT_API_KEY: {{ .Values.config.qdrant.apiKey }}
  QUANTIZE_VECTORS: {{ .Values.config.qdrant.quantizeVectors | quote }}
  QDRANT_SHARD_COUNT: {{ .Values.config.qdrant.shardCount | quote }}
  REPLICATION_FACTOR: {{ .Values.config.qdrant.replicationFactor | quote }}
  VECTOR_SIZES: {{ join "," .Values.config.qdrant.vectorSizes | quote }}
  {{- if .Values.config.smtp.relay }}
  SMTP_RELAY: {{ .Values.config.smtp.relay }}
  {{- end }}
  {{- if .Values.config.smtp.username }}
  SMTP_USERNAME: {{ .Values.config.smtp.username }}
  {{- end }}
  {{- if .Values.config.smtp.password }}
  SMTP_PASSWORD: {{ .Values.config.smtp.password }}
  {{- end }}
  {{- if .Values.config.smtp.emailAddress }}
  SMTP_EMAIL_ADDRESS: {{ .Values.config.smtp.emailAddress }}
  {{- end }}
  OPENAI_API_KEY: {{ .Values.config.openai.apiKey }}
  LLM_API_KEY: {{ .Values.config.llm.apiKey }}
  SECRET_KEY: {{ .Values.config.trieve.secretKey | quote }}
  SALT: {{ .Values.config.trieve.salt }}
  {{- if .Values.config.s3.endpoint }}
  S3_ENDPOINT: {{ .Values.config.s3.endpoint }}
  {{- end }}
  {{- if .Values.config.s3.accessKey }}
  S3_ACCESS_KEY: {{ .Values.config.s3.accessKey }}
  {{- end }}
  {{- if .Values.config.s3.secretKey }}
  S3_SECRET_KEY: {{ .Values.config.s3.secretKey }}
  {{- end }}
  {{- if .Values.config.s3.bucket }}
  S3_BUCKET: {{ .Values.config.s3.bucket }}
  {{- end }}
  {{- if .Values.config.s3.region }}
  AWS_REGION: {{ .Values.config.s3.region }}
  {{- end }}
  {{- if .Values.config.pagefind_s3.endpoint }}
  S3_ENDPOINT_PAGEFIND: {{ .Values.config.pagefind_s3.endpoint }}
  {{- end }}
  {{- if .Values.config.pagefind_s3.accessKey }}
  S3_ACCESS_KEY_PAGEFIND: {{ .Values.config.pagefind_s3.accessKey }}
  {{- end }}
  {{- if .Values.config.pagefind_s3.secretKey }}
  S3_SECRET_KEY_PAGEFIND: {{ .Values.config.pagefind_s3.secretKey }}
  {{- end }}
  {{- if .Values.config.pagefind_s3.bucket }}
  S3_BUCKET_PAGEFIND: {{ .Values.config.pagefind_s3.bucket }}
  {{- end }}
  {{- if .Values.config.pagefind_s3.region }}
  AWS_REGION_PAGEFIND: {{ .Values.config.pagefind_s3.region }}
  {{- end }}
  COOKIE_SECURE: {{ .Values.config.trieve.cookieSecure | quote }}
  TIKA_URL: tika.default.svc.cluster.local
  OPENAI_BASE_URL: {{ .Values.config.openai.baseUrl }}
  {{- if .Values.config.stripe.secret }}
  STRIPE_SECRET: {{ .Values.config.stripe.secret }}
  {{- end }}
  {{- if .Values.config.stripe.webhookSecret }}
  STRIPE_WEBHOOK_SECRET: {{ .Values.config.stripe.webhookSecret }}
  {{- end }}
  ADMIN_DASHBOARD_URL: {{ .Values.config.vite.dashboardUrl }}
  OIDC_CLIENT_SECRET: {{ .Values.config.oidc.clientSecret }}
  OIDC_CLIENT_ID: {{ .Values.config.oidc.clientId }}
  OIDC_AUTH_REDIRECT_URL: {{ .Values.config.oidc.authRedirectUrl }}
  OIDC_ISSUER_URL: {{ .Values.config.oidc.issuerUrl }}
  BATCH_CHUNK_LIMIT: {{ .Values.config.trieve.batch_limit | default 120 | quote }}
  SPARSE_SERVER_QUERY_ORIGIN: {{ .Values.config.trieve.sparseServerQueryOrigin }}
  SPARSE_SERVER_DOC_ORIGIN: {{ .Values.config.trieve.sparseServerDocOrigin }}
  EMBEDDING_SERVER_ORIGIN: {{ .Values.config.trieve.embeddingServerOrigin }}
  EMBEDDING_SERVER_ORIGIN_BGEM3: {{ .Values.config.trieve.embeddingServerOriginBGEM3 }}
  EMBEDDING_SERVER_ORIGIN_JINA_CODE: {{ .Values.config.trieve.embeddingServerOriginJinaCode }}
  JINA_CODE_API_KEY: {{ .Values.config.trieve.jinaCodeApiKey }}
  RERANKER_SERVER_ORIGIN: {{ .Values.config.trieve.rerankerServerOrigin }}
  UNLIMITED: {{ .Values.config.trieve.unlimited | quote }}
  REDIS_CONNECTIONS: "30"
  CLICKHOUSE_URL: {{ .Values.config.analytics.clickhouseUrl | quote }}
  CLICKHOUSE_DB: {{ .Values.config.analytics.clickhouseDB | quote }}
  CLICKHOUSE_USER: {{ .Values.config.analytics.clickhouseUser | quote }}
  CLICKHOUSE_PASSWORD: {{ .Values.config.analytics.clickhousePassword | quote }}
  USE_ANALYTICS: {{ .Values.config.analytics.enabled | quote }}
  BM25_ACTIVE: {{ .Values.config.trieve.bm25Active | quote }}
  SUBTRACE_TOKEN: {{ .Values.config.trieve.subtraceToken | quote }}
  FIRECRAWL_URL: {{ .Values.config.trieve.firecrawlUrl | quote }}
  DITTOFEED_API_KEY: {{ .Values.config.trieve.dittofeedApiKey | quote }} 
  CREATE_QDRANT_COLLECTIONS: {{ .Values.config.qdrant.initCollections | quote }} 
  CHAT_COMPLETION_TIMEOUT_SECS: {{ .Values.config.trieve.chatCompletionTimeoutSecs | quote }}
  {{- if .Values.config.trieve.youtubeApiKey }}
  YOUTUBE_API_KEY: {{ .Values.config.trieve.youtubeApiKey | quote }}
  {{- end }}
  PAGEFIND_CDN_BASE_URL: {{ .Values.config.trieve.pagefindCdnUrl }}
  BATCH_ETL_URL: {{ .Values.config.trieve.batchEtlUrl }}
