apiVersion: batch/v1
kind: CronJob
metadata:
  name: clustering-cronjob
spec:
  schedule: "1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: clustering-task
              image: {{ printf "%s:%s" "trieve/clickhouse-clustering" .Values.containers.clustering_cron.tag }}
              imagePullPolicy: IfNotPresent
              env:
                - name: ANTHROPIC_API_KEY
                  value: {{ .Values.config.trieve.anthropicAPIKey | quote }}
                - name: CLICKHOUSE_DSN
                  value: {{ .Values.clickhouse.dsn }}
          restartPolicy: Never
